// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TurntablRoleManager.API.DbContexts;

namespace TurntablRoleManager.API.Migrations
{
    [DbContext(typeof(TurntablDbContext))]
    [Migration("20200422190323_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TurntablRoleManager.API.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(1500)")
                        .HasMaxLength(1500);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            CreatedAt = new DateTime(1650, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Devloping and Managing Application",
                            Name = "Developer"
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba96"),
                            CreatedAt = new DateTime(1650, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Maninging project for the company",
                            Name = "Project Manager"
                        },
                        new
                        {
                            Id = new Guid("2902b665-1190-4c70-9915-b9c2d7680450"),
                            CreatedAt = new DateTime(1701, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Maninging accounts for the company",
                            Name = "Accountant"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
